name: SAST Scan
env:
  V_ID: ${{ secrets.VERACODE_API_ID }}
  V_KEY: ${{ secrets.VERACODE_API_KEY }}
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -B package --file app/pom.xml
    - name: wrapper
      run: |
        wget https://tools.veracode.com/integrations/API-Wrappers/Java/bin/VeracodeJavaAPI.zip
    - name: Veracode Upload And Scan
      uses: veracode/veracode-uploadandscan-action@master
      with:
        appname: Verademo GitHub
        createprofile: true
        createsandbox: true
        canjobfail: true
        version: ${{ github.run_id }}
        filepath: app/target/verademo.war
        sandboxname: Github-Sandbox
        deleteincompletescan: 2
        debug: true
        vid: ${{secrets.VERACODE_API_ID}}
        vkey: ${{secrets.VERACODE_API_KEY}}
        scantimeout: 60
